### ISSUE TITLE
Offline contacts are not shown.

### ISSUE THREAD

**Issue by SkyzohKey** [RicinApp/Ricin#11]

**Comment by gmscs** [comment]
Isn't offline contacts not being shown related to this?

> this.tox.friend_online.connect ((friend) => { ... });

(MainWindow.vala - lines 146 - 157)

doesn't this mean that we're only giving them a position if they have already connected (come online) at some point? Should be changed to giving contacts a position as soon as they're loaded from the file rather than giving them a position only when they've connected.

**Comment by SkyzohKey** [comment]
Yep, but I don't know how to get contacts from the .tox file. :x

**Comment by gmscs** [comment]
https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.h#L1151
thanks to BlameAliens from the irc

**Comment by SkyzohKey** [comment]
Since this is fixed, I close the issue. Fixed in wip/sidebar.

**Comment by gmscs** [comment]
The issue is fixed on wip/sidebar. We should close issues when they are merged into the master branch **only**. This is an issue that should have been merged into master. When an issue is fixed on another branch please just add a comment to the issue saying that it is fixed and will be closed when the branch is merged. 
The fix isn't complete either; missing:
- [x] Name should show, not toxID
- [x] User status should be shown, instead of "last seen"
- [x] Status image (offline image)

**Comment by SkyzohKey** [comment]
I tried to make username and status message showing when user is offline, but it seems to be a toxcore issue. :x

**Comment by SkyzohKey** [comment]
Since this is fixed, the issue can be closed. :)
