### ISSUE TITLE
Group chat support

### ISSUE THREAD

**Issue by SilverRainZ** [RicinApp/Ricin#141]
It seems that ricin still no supports temp group. Do you plan to implement it?

**Comment by SkyzohKey** [comment]
Yep i'm working on current groupchats, they should be ready in 1 or 2 weeks ;)

**Comment by quininer** [comment]
any news?

**Comment by SkyzohKey** [comment]
I didn't make any progress on groupchats as I still don't know if the new one will ever come or not. :x

**Comment by SkyzohKey** [comment]
This issue has been inactive for several months now, thus closing.
In the future, feel free to create a new issue instead of keeping posting to this one.

Note: Groupchats are planed in the complete rewrite I started in the `rewrite-clean` branch. I decided i'll implement current groupchats and use custom Tox packets to perform missing stuffs. New groups won't ever been merged i guess, so that's the best option IMHO.
