### ISSUE TITLE
download impossible

### ISSUE THREAD

**Issue by FiSHYsolutions** [RicinApp/Ricin#163]
obviously readme.md isn't up to date.

`wget https://cdn.ricin.im/linux/ricin-0.2.1.app` (as suggested)

results in:
`ERROR 523: Origin Unreachable.`

tried to download `https://cdn.ricin.im/windows/ricin-0.1.1-win32_x86-64.zip` (as suggested)

results in:
`Error 523 - Origin is unreachable`

**Comment by SkyzohKey** [comment]
That's normal, Ricin is now officially deprecated, please use another client :)

**Comment by ProMcTagonist** [comment]
If Ricin is dead, please make a note of this at the top of the README.

**Comment by SkyzohKey** [comment]
@ProMcTagonist The "unmaintained-dont-use" topic should help with that, updating the README should occurs soon ;)

**Comment by verymilan** [comment]
w000000t? where is this topic? :o

**Comment by SkyzohKey** [comment]
@tchncs At the bottom of the main Github page for Ricin. :) Now working on [Konv](https://github.com/SkyzohKey/Konv).

**Comment by smaragdus** [comment]
@SkyzohKey
Ricin had been discontinued before it became usable, this is not good. I cannot trust your future projects.

**Comment by AyoungDukie** [comment]
I am slightly confused, but I think I follow. Konv is going to be Ricin v2. Out of curiosity, why the name change? Is it branding, or was the rewrite bigger than originally thought?

**Comment by SkyzohKey** [comment]
That's the big rewrite which is planed since ages and I finaly found the motivation to make it happens. Name changed because I lost the ricin.im domain name, so bought konv.im.

@smaragdus Ricin was a PoC that a Tox client could be written in Vala. Now that I've seen it could works nice, I'm rewriting the whole app with cleaner code, tests and c-toxcore. This is a sort of Ricin v.2

**Comment by verymilan** [comment]
A rewrite from ricin.im to konv.im would be nice since i list my translation work as engagement reference to my applications (not software applications xD)... .
Also it is less confusing for old ricin users - you tried to announce this program as simple for everyone and now potencial users see the page deleted and just away.
You cannot expect a simple user to search the git repository for issues with hints about the future of ricin.
 
Hm but i guess this domain is completly deleted already hm?

Edit: by the way, konv.im still announces as ricin messenger and has broken images...

**Comment by SkyzohKey** [comment]
@tchncs Yep website should be back soon, i have to work on it. Also, konv.im will have a clean code thus allowing me to make correct support for a/v and screensharing. All of that with decent UI/UX and cross-platform support.

Anyway thanks again in the interest you give to my projects mate. :)

**Comment by dnkls** [comment]
Plz bro help download and compile for windows , https://ricin.im/downloads.html#windows is off line(((

**Comment by SkyzohKey** [comment]
@dnkls please read the whole conversation, I explained why this link isn't working anymore, sorry for the inconvenience. 🙂

**Comment by smaragdus** [comment]
**@SkyzohKey**
Is the development of the Windows version abandoned?

**Comment by AyoungDukie** [comment]
I believe the project development has migrated to Konv.im (essentially a project renaming).
